language: python
python: 2.7
branches:
  only:
    - lektor
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - pip install git+https://github.com/singingwolfboy/lektor.git@fix-ghpages-https-deploy#egg=lektor
script: "lektor build --no-prune"
deploy:
  provider: script
  script: "lektor deploy ghpages-https"
  on:
    branch: lektor
